### ISSUE TITLE
dEssentials: compile program

### ISSUE THREAD

**Issue by mcmonkey4eva** [mcmonkey4eva/DenizenScripts#20]
A program that auto-compiles the full set of scripts into one big super-script for repo purposes would be super useful.

**Comment by Morphan1** [comment]
Why not add this as a tool in the dScript IDE?

**Comment by mcmonkey4eva** [comment]
One daaaaaaaaaaaaaayyyyyyyyyyyyyyyyyyyy

**Comment by mcmonkey4eva** [comment]
needs to be compiled in mono still actually
